### PR TITLE
[WIP] Python 3 Support

### PR DESCRIPTION
**Pull request by emmett9001**

### CODE REVIEW

**Comment by dan-blanchard** [comment]
Python 3! :+1:

**Comment by kbourgoin** [comment]
Before this goes in, we're going to need a lot of testing.  Tbh, py3 support wasn't planned to be a priority until the next release.

**Comment by kbourgoin** [comment]
Relates to issue #120.

**Comment by emmett9001** [comment]
Oh yeah, I was just looking for something to pick off this morning. I don't expect to put this in the coming release, but hopefully the following one.

**Comment by kbourgoin** [comment]
Absolutely the following one, probably with lots of input from @dan-blanchard too. :)

**Comment by jklukas** [comment]
Is there any sense of the ETA on a release with Python 3 support? I'm building a project right now that I'd love to use `pykafka` for, but I might have to revert to `kafka-python` if compatibility just isn't in the cards.

**Comment by emmett9001** [comment]
Python 3 compatibility is slated for the next pykafka release, which we hope to have ready in the next few months. The main concerns for that release are the asynchronous producer implementation and python 3 support. You can track the progress of this release [here](https://github.com/Parsely/pykafka/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.2.0).

**Comment by jklukas** [comment]
Thanks for the update, @emmett9001.

**Comment by sontek** [comment]
This looks like it doesn't merge anymore.  This seems more up to date than #106 but we should probably merge branches together so people like me who want python3 support can help contribute :)

**Pull request closed without merging**
