### PR TITLE
Add CPython 3.5 as a supported version

### PR DESCRIPTION
**Pull request by dirn**

### CODE REVIEW

**Comment by dirn** [comment]
The build is failing because of https://github.com/travis-ci/travis-ci/issues/4794. Any preference on an approach to take (`deadsnakes` versus `matrix` versus switching tox to run under 3.5)? I'll be happy to update this pull request.

**Comment by emmett9001** [comment]
I think continuing to use `tox` is most preferable. Does telling travis to use 3.5 preclude the use of other interpreters via `tox`?

**Comment by yungchin** [comment]
There's also https://github.com/ryanhiebert/tox-travis which I've been meaning to try out but haven't got to. That would potentially clean up the travis config a little, getting rid of the repetitive env declarations.

**Comment by dirn** [comment]
None of the suggested changes remove tox. They only relate to how CPython 3.5 is made available in the current Travis images. Telling Travis to use 3.5 (my vote) won't remove other interpreters from the image; it just forces Travis to use an image that has it installed.

**Comment by emmett9001** [comment]
Sounds great to me - if you can make that change and get this branch to pass travis, this may be an easy inclusion.

**Comment by yungchin** [comment]
@dirn there are [a couple of failures on travis-ci][0], none of which are really due to anything you're doing. The failures on py34 and py35 are due to testinstances' py3-compatibility fixes not having been sent to pypi yet, I'll file a ticket to request a release.

@emmett9001 the [other failure][1], on py27, worries me a bit - it's the second or third time it's popped up on travis-ci now and seems to have been recently introduced, but I've never seen this in local testing.

[0]: https://travis-ci.org/Parsely/pykafka/builds/85192931
[1]: https://travis-ci.org/Parsely/pykafka/jobs/85192932

**Comment by dirn** [comment]
Let me document the path I've taken to get to the current state of `.travis.yml`. Note that running tox locally results in no failures, so everything below is related specifically to Travis.

I first took the approach discussed.

    python:
      - "3.5"

This caused Travis to use 3.5 to run tox. While this change should have been sufficient, tests failed across multiple interpreters.

Next I tried specifying all of the tested interpreters.

    python
      - "2.7"
      - "3.4"
      - "3.5"
      - "pypy"

This resulted in each test being run with each interpreter, meaning 16 tests were run (four interpreters and 4 environments). In hindsight I should have seen this coming but mistakenly thought I was specifying a list of interpreters to include.

Finally I settled on a build matrix. Travis's build matrices allow you to specify environments for each interpreter.

Once the tests get to a better state (as alluded to by @yungchin), I believe the first approach will still work. Simple solutions are often the best, especially when it's all just a workaround to deal with Travis being behind in adding 3.5 to their Python images.

**Comment by emmett9001** [comment]
Running this branch locally, I get a missing interpreter error for 3.5. Also, I'm ok with some travis tests hanging - that's been happening a lot lately. As long as we can be confident that the hanging tests aren't related to these changes, it doesn't need to block a merge.

**Comment by dirn** [comment]
@emmett9001 do you have 3.5 installed locally? If not, tox won't be able to find it.

**Comment by emmett9001** [comment]
I can get all tests to pass locally except for 3.5, which is showing the [same failures](https://travis-ci.org/Parsely/pykafka/jobs/85192935) as on Travis. 3.4 tests are [also failing](https://travis-ci.org/Parsely/pykafka/jobs/85192933) on Travis - something to do with the kafka binary installation, it seems.

**Comment by rduplain** [comment]
Depends on Parsely/testinstances#7.

**Comment by emmett9001** [comment]
Testinstances release got Travis tests to pass, I'm still working on my local setup. Currently the 3.5 tests fail for me with [this error](https://gist.github.com/emmett9001/de547ada83687a7c1252)

**Comment by emmett9001** [comment]
Tests passing locally and in Travis.

**Pull request merged**
