### PR TITLE
Adding support for Python 3.x

### PR DESCRIPTION
**Pull request by thedrow**
Also --use-mirrors is deprecated.

[Review on Reviewable](https://reviewable.io/reviews/parsely/pykafka/106)

### CODE REVIEW

**Comment by kbourgoin** [comment]
Hi there!

My apologies that this was basically abandonware of the past half year.  We're currently ramping up development in order to get 0.8.2 support.  We've also renamed the project to PyKafka ahead of that release.

I wasn't planning on python 3 support for the current release, but if you're still interested in contributing I'd love to add it.  I've moved main development to the master branch since Kafka 0.7.x is pretty well dead.

Thanks,

Keith.

**Comment by thedrow** [comment]
Can you please restart the latest build in order to see what's broken?
I can't promise to add Python 3 support if there is a lot of work involved.

**Comment by kbourgoin** [comment]
I'll try to get travis working again ASAP. The master branch is in flux because 0.8 support required a near rewrite. I'll update this PR when it's back.

**Comment by emmett9001** [comment]
Closed in favor of https://github.com/Parsely/pykafka/pull/231

**Pull request closed without merging**
