### PR TITLE
Test in Travis with the latest Kafka 0.8.x release

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by emmett9001** [comment]
@thedrow What does this get us that testing with 0.8.2.1 doesn't? I'd prefer to test the oldest possible compatible release if we're only going to test one of the 0.8.2 series.

**Comment by thedrow** [comment]
Usually people prefer to test with the latest stable release.
Feel free to close this PR if it's not required.

**Comment by emmett9001** [comment]
@rduplain Do you have an opinion on this? I don't feel too strongly one way or the other, but I'd like to avoid testing both bugfix versions.

**Comment by thedrow** [comment]
@emmett9001 There was a serious snappy bug fixed in 0.8.2.2.
We should recommend upgrading anyway.

**Comment by thedrow** [comment]
:+1:

**Pull request merged**
