### PR TITLE
Disable Kafka-unsupported lz4 dependent blocks

### PR DESCRIPTION
**Pull request by carsonip**
Specify in lz4 compress to not use dependent blocks.

### CODE REVIEW

**Comment by carsonip** [comment]
This commit is identical to https://github.com/dpkp/kafka-python/commit/afc6346d05054faf75e30a01b9e41a9916e703a9

**Comment by emmett9001** [comment]
This changeset looks great, thanks for putting in the extra effort to add a test that validates this case. Travis is showing some [failures](https://github.com/Parsely/pykafka/pull/915/checks?check_run_id=62142148) that look like they're originating with rdkafka, so we'll have to figure out what's going on there. Aside from that, though, this looks close to mergeable.

**Comment by emmett9001** [comment]
It looks possible that `parameterized` is somehow causing the rdkafka tests to fail. Maybe try setting up the new tests without the use of that library?
```
______ TestRdKafkaProducer.test_sync_produce_compression_large_message_0 _______
a = (<tests.pykafka.test_producer.TestRdKafkaProducer testMethod=test_sync_produce_compression_large_message_0>,)
    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)
.tox/py27/lib/python2.7/site-packages/parameterized/parameterized.py:518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/pykafka/test_producer.py:390: in test_sync_produce_compression_large_message
    consumer = self._get_consumer()
tests/pykafka/test_producer.py:66: in _get_consumer
    **kwargs
pykafka/topic.py:265: in get_simple_consumer
    **kwargs)
pykafka/simpleconsumer.py:244: in __init__
    self.start()
pykafka/simpleconsumer.py:296: in start
    self.reset_offsets()
pykafka/simpleconsumer.py:727: in reset_offsets
    response = broker.request_offset_limits(reqs)
pykafka/broker.py:45: in wrapped
    return fn(self, *args, **kwargs)
pykafka/broker.py:355: in request_offset_limits
    return future.get(response_class)
```

**Comment by carsonip** [comment]
I noticed the test fail yesterday too. I'll debug this later today.

**Comment by carsonip** [comment]
My feeling was that it was more about `rdkafka` than `parameterized`. After changing the code to a for-loop, I still get the error.
```
self = <tests.pykafka.test_producer.TestRdKafkaProducer testMethod=test_sync_produce_compression_large_message>

    def test_sync_produce_compression_large_message(self):
        for compression_type in [CompressionType.NONE, CompressionType.GZIP, CompressionType.SNAPPY, CompressionType.LZ4]:
    
>           consumer = self._get_consumer()

tests/pykafka/test_producer.py:386: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/pykafka/test_producer.py:66: in _get_consumer
    **kwargs
pykafka/topic.py:265: in get_simple_consumer
    **kwargs)
pykafka/simpleconsumer.py:244: in __init__
    self.start()
pykafka/simpleconsumer.py:296: in start
    self.reset_offsets()
pykafka/simpleconsumer.py:727: in reset_offsets
    response = broker.request_offset_limits(reqs)
pykafka/broker.py:45: in wrapped
    return fn(self, *args, **kwargs)
pykafka/broker.py:355: in request_offset_limits
    return future.get(response_class)
```

**Comment by carsonip** [comment]
@emmett9001 The error is caused by the test `test_recover_disconnected`. If you remove this test, everything works well. This problematic test somehow breaks the consumer reset offset function after disconnecting for rdkafka.

**Comment by emmett9001** [comment]
@carsonip I wonder what happens if you move `test_recover_disconnected` to be the very last test that runs, even after your newly added test. I bet that will let us merge this PR without having to block on fixing the broken test.

**Comment by carsonip** [comment]
@emmett9001 There are 2 changes:
1. The faulty test is moved to the last.
2. librdkafka supports lz4 compression from v0.9.2 but requires liblz4-dev for librdkafka version <0.9.5. They only had in-tree built liblz4 from v0.9.5. See  [v0.9.5 release notes](https://github.com/edenhill/librdkafka/releases/tag/v0.9.5). I have added liblz4-dev dependency in travis config, but we could simply use librdkafka v0.9.5 in travis.

I expect the test to pass soon (it is still running now).

**Comment by carsonip** [comment]
Well, it failed again. I cannot reproduce the python 3.5 + rdkafka one. Any comment on Pypy fails?

**Comment by emmett9001** [comment]
It [looks possible](https://github.com/python-lz4/python-lz4/issues/20) that the python lz4 library doesn't fully support PyPy. To facilitate this PR getting merged, I think it's fine to ignore the lz4 test when running under PyPy, as in [this example](https://github.com/Parsely/pykafka/blob/c816efae85625f4d8064cf9241b616bb6128c834/tests/pykafka/test_balancedconsumer.py#L525). The use of `parameterized` might make using this decorator a bit difficult, so the right answer might just be to do something like [this conditional skip](https://github.com/Parsely/pykafka/blob/c816efae85625f4d8064cf9241b616bb6128c834/tests/pykafka/test_balancedconsumer.py#L465-L466) for PyPy specifically. Once that test is skipped, this PR should be mergeable.

**Comment by carsonip** [comment]
How can we trigger a rebuild? The failure was just unlucky probably.

**Comment by emmett9001** [comment]
If you click "Details" next to the Travis CI check, you'll get a view of the build. From there, click on the job number of the failed job, then click Restart Job on the Travis job page. I've gone ahead and done this for the current build.

**Comment by emmett9001** [comment]
Thanks for the awesome work and for seeing this through multiple edits, @carsonip!

**Comment by carsonip** [comment]
> If you click "Details" next to the Travis CI check, you'll get a view of the build. From there, click on the job number of the failed job, then click Restart Job on the Travis job page. I've gone ahead and done this for the current build.

I suppose that is only accessible for repo owners. Never mind. Thanks!

**Pull request merged**
