### PR TITLE
Break Cluster-Topic refcycle

### PR DESCRIPTION
**Pull request by yungchin**
This partially addresses #257, as discussed there. I figured it was best to make a separate pullreq, as it doesn't have much to do with the changes in #258.

### CODE REVIEW

**Comment by yungchin** [comment]
As noted in the last commit msg, this now also happens to deal with #175 - topic auto-creation is enabled even on a fresh, empty cluster (there's still no broker metadata, but it can fall back on the bootstrap brokers).

**Comment by emmett9001** [comment]
@yungchin thanks for making this totally separate from #258 - it makes them both a lot easier to think about.

**Comment by emmett9001** [comment]
I've spent a while trying to grok this, and I understand it satisfactorily. Even outside of the specific object-leak bugfix, lazily creating `Topic`s is a good idea to mitigate memory usage. I'd like to run a few more tests on my own, but I'm close to totally convinced.

**Comment by yungchin** [comment]
@emmett9001 thanks for checking this out! I was a bit spooked by the two test failures on travis just now:
https://travis-ci.org/Parsely/pykafka/jobs/81294673#L516

Have not seen these in local testing, but to save me some RAM I often run a two-node cluster (whereas we run a three-node cluster on travis), and I guess the smaller cluster is quicker to finish setting up a new topic.

In the failing tests, I think what goes wrong is this: `test_topic_autocreate` tries to auto-create a topic but gives up on it too soon (the cluster is still electing a leader and stuff), and so the test fails. Then  we enter `test_topic_updates`, and in the middle of that our new topic from `test_topic_autocreate` finally appears, so now this test errors too because it sees more new topics than it expected. (And both tests are new, which is why this has never come up before, but this seems to be the kind of failure that will keep coming up randomly....)

I'm not really sure what the best fix would be - I suppose `TopicDict._create_topic` needs to wait longer or should really be smarter about the wait, but I've no good suggestions on that :(

**Comment by yungchin** [comment]
Out of curiosity, I restarted the test on travis earlier (the previous run's log output is [here][0] for posterity and such), and indeed it passed just fine the second time around. Of course that doesn't mean it's all ok - the test would continue to occasionally fail. The commit I've just pushed should fix that.

[0]: https://gist.github.com/yungchin/1ee48453b23a1319d4f4

**Pull request merged**
