### PR TITLE
Cache pip in Travis

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by yungchin** [comment]
Thanks very much for this. We'd been meaning to look into the caching options for a while. One concern we had was that it might potentially cause oddities when the cache is stale - so one question @thedrow: do you know if clearing the travis cache is quickly done?

Also, provided that @emmett9001 is also happy with caching, I'd have another feature req for this PR - could we also cache the `KAFKA_BIN` path (where testinstances puts the kafka and zk binaries)?

Many thanks!

**Comment by thedrow** [comment]
You can easily clear the cache from the settings tab or the command line if something goes wrong which is almost never, at least with pip.

**Comment by thedrow** [comment]
I added a cache to $HOME/kafka-bin. Not sure if it will speed things up since the cache is just S3.

**Comment by thedrow** [comment]
We can also cache the compilation of librdkafka. I'll try that as well.

**Comment by emmett9001** [comment]
I just ran into trouble with the kafka binary caching in #416. Since a single Travis build needs to test multiple versions of kafka, I'll remove the caching on that directory for now.

**Comment by thedrow** [comment]
The problem is with Travis. They don't namespace cache buckets according to environment variables correctly. It's a known issue and they are working on a fix.

**Pull request merged**
