### PR TITLE
[WIP] Raise worker exceptions

### PR DESCRIPTION
**Pull request by emmett9001**
This pull request uses the same method in use in `Producer` to surface exceptions encountered on worker threads to the main thread. This can potentially help with the issue seen in #224, #223, and #189.

### CODE REVIEW

**Comment by ltucker** [comment]
@emmett9001 when you say it can help with the listed consumer issues, is the idea that an application would catch SocketDisconnected (and whatever else) and establish an new Consumer instance when there is a failure on any individual broker connection?

**Comment by emmett9001** [comment]
The basic idea behind this pull request is that client code could catch these exceptions and instantiate a new consumer. However, this pull request is still very experimental. I haven't given much thought to what it actually looks like from the client perspective. I certainly wouldn't want clients to have to care about the internal connection objects.

**Comment by rduplain** [comment]
Current status: need to replicate error and confirm that this fixes it.

**Comment by rduplain** [comment]
This work is on-going (I had an incorrect comment there briefly, which is now deleted).

**Pull request merged**
